components:
  - name: frontend
    replicas: 1
    image: thatqa/release-calendar-frontend:0.0.1
    service:
      enabled: true
      type: ClusterIP
      port: 80
      targetPort: 3000
    env:
      - name: NEXT_PUBLIC_API_BASE
        value: "/api"

  - name: backend
    replicas: 1
    image: thatqa/release-calendar-api:0.0.1
    service:
      enabled: true
      type: ClusterIP
      port: 80
      targetPort: 8080
    env:
      - name: TZ
        value: "UTC"
      - name: BACKEND_PORT
        value: "8080"
      - name: DB_HOST
        value: "mariadb"
      - name: DB_PORT
        value: "3306"
      - name: DB_USER
        value: "user"
      - name: DB_PASS
        value: "password"
      - name: DB_NAME
        value: "release-calendar"

  - name: nginx
    image: nginx:1.27-alpine
    replicas: 1
    service:
      enabled: true
      type: ClusterIP
      port: 80
      targetPort: 80
    configFilename: default.conf
    config: |
      server {
        listen 80;
        server_name _;

        client_max_body_size 20m;

        location /api/ {
          proxy_http_version 1.1;
          proxy_set_header Connection "";
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_pass http://{{ $.Chart.Name }}-backend:8080/;
        }

        location / {
          proxy_http_version 1.1;
          proxy_set_header Connection "";
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_pass http://{{ $.Chart.Name }}-frontend/;
        }
      }
    volumes:
      - name: nginx-conf
        configMap:
          name: "{{ $.Chart.Name }}-nginx-conf"
          items:
              - key: default.conf
                path: default.conf
    volumeMounts:
      - name: nginx-conf
        mountPath: /etc/nginx/conf.d/default.conf
        subPath: default.conf
    ingress:
      enabled: true
      className: nginx
      host: release.calendar
      annotations: { }
      tls: [ ]

migrations:
  enabled: true
  image: thatqa/release-calendar-api:0.0.1
  args: ["migrate"]
  backoffLimit: 1
  ttlSecondsAfterFinished: 300
  env:
    - name: TZ
      value: "UTC"
    - name: BACKEND_PORT
      value: "8080"
    - name: DB_HOST
      value: "mariadb"
    - name: DB_PORT
      value: "3306"
    - name: DB_USER
      value: "user"
    - name: DB_PASS
      value: "password"
    - name: DB_NAME
      value: "release-calendar"