{{- range .Values.components }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Chart.Name }}-{{ .name }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/component: {{ .name }}
spec:
  replicas: {{ .replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: {{ .name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/component: {{ .name }}
      {{- with .podAnnotations }}
      annotations:
{{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .serviceAccountName }}
      serviceAccountName: {{ . }}
      {{- end }}

{{- with .volumes }}
      volumes:
{{ tpl (toYaml .) $ | nindent 8 }}
{{- end }}

      containers:
        - name: {{ .name }}
          image: {{ .image | quote }}
          {{- with .imagePullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}

          {{- with .containerPort }}
          ports:
            - containerPort: {{ . }}
          {{- end }}

          {{- with .command }}
          command:
{{ toYaml . | nindent 12 }}
          {{- end }}

          {{- with .args }}
          args:
{{ toYaml . | nindent 12 }}
          {{- end }}

          {{- with .env }}
          env:
{{ toYaml . | nindent 12 }}
          {{- end }}

          {{- if .envFrom }}
          envFrom:
{{ toYaml .envFrom | nindent 12 }}
          {{- else if .envFromSecrets }}
          envFrom:
            {{- range .envFromSecrets }}
            - secretRef:
                name: {{ .name }}
            {{- end }}
          {{- end }}

{{- with .volumeMounts }}
          volumeMounts:
{{ tpl (toYaml .) $ | nindent 12 }}
{{- end }}

          {{- with .resources }}
          resources:
{{ toYaml . | nindent 12 }}
          {{- end }}
---
{{- end }}
