{{- range $name, $c := .Values.components }}
{{- if and $c.service $c.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Chart.Name }}-{{ $name }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/component: {{ $name }}
  {{- with $c.service.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ default "ClusterIP" $c.service.type }}
  selector:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $name }}
  ports:
    - name: {{ default "http" $c.service.portName }}
      port: {{ $c.service.port }}
      targetPort: {{ default $c.containerPort $c.service.targetPort }}
---
{{- end }}
{{- end }}
